### PR TITLE
Added: Arkansas Scraper

### PR DESCRIPTION
**Pull request by billykern**

### CODE REVIEW

**Comment by ajb** [comment]
Awesome! Will look and hopefully merge shortly.

On Mon, Sep 15, 2014 at 1:21 AM, billykern notifications@github.com wrote:

> ---
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/billykern/openrfps-scrapers master
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/dobtco/openrfps-scrapers/pull/26
> Commit Summary
> - created config.yml
> - get solicitation URLs
> - getSolicitationDetails
> - validated with test-scraper
> - added config.yml
> 
> File Changes
> - _A_ scrapers/ar/config.yml
>   https://github.com/dobtco/openrfps-scrapers/pull/26/files#diff-0 (2)
> - _A_ scrapers/ar/rfps.js
>   https://github.com/dobtco/openrfps-scrapers/pull/26/files#diff-1
>   (59)
> 
> Patch Links:
> - https://github.com/dobtco/openrfps-scrapers/pull/26.patch
> - https://github.com/dobtco/openrfps-scrapers/pull/26.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dobtco/openrfps-scrapers/pull/26.

## 

Adam Becker
510.928.9111
@AdamJacobBecker

**Comment by billykern** [comment]
Thanks for taking a look! First actual pull request attempt, hope it isn't TOO far off, any feedback appreciated...

**Comment by ajb** [comment]
Heh, only 5 RFPs right now! Looks great though, merging :)

**Comment by billykern** [comment]
Awesome, thanks again!

**Pull request merged**
