### PR TITLE
alabama scraper

### PR DESCRIPTION
**Pull request by ghost**
Scraper working and tests are passing.

I noticed right as I was finishing up that the site that was on the wiki for Alabama linked to Invitations to Bid (ITBs) rather than Requests for Proposals (RFPs). After poking around the web a bit, I got the impression that the process for bidding on an ITB would be different than for an RFP and thought that it might make the data even richer and more valuable to distinguish between the two.

To that extent, I named the scraper `itbs.coffee` and added a Boolean field `is_itb` to each JSON object returned, which is `true` if the solicitation is an ITB and not an RFP. I also added the `is_itb` field to the schema doc. 

Lemme know if that seems like overkill or if we're not as concerned with ITBs than RFPs. In either case, I'm happy to write another whosie whatsit for Alabama's proper RFPs.

### CODE REVIEW

**Comment by ajb** [comment]
Hmm, I've personally never heard the term "ITB". Let me discuss with the team before merging.

Regardless, awesome!

**Comment by ghost** [comment]
Sgtm! In case it's helpful, [this](http://www.onvia.com/business-resources/articles/responding-ifb-rfp-or-rfq) is the page I was looking at last night. Rereading it this morning I'm a little less sure of my decision, but regardless I'm happy to do whatever you guys think is best.

**Comment by sidburgess** [comment]
I can shed some light on this.

ITBs are similar to RFQ, or Request for Quotes. This type of procurement
vehicle is typically used for more commodity type purchasing. The
deliverable is really just the product at a basic unit cost. e.g. truck
chassis for a F-150.

An RFP includes more information about the project and how it is going to
be accomplished by the bidding vendor. Because of the range of options that
will be received, they are oftentimes "Best Value" awards. This just means
that the agency doesn't have to go with the lowest bid, but can instead
award the contract they believe will deliver the best value to the agency.
Hence the complicated scoring and seemingly endless disclaimers. Everyone
in that process is trying to CYA.

s

On Tue, Feb 25, 2014 at 9:29 AM, Kiran Gollakota
notifications@github.comwrote:

> Sgtm! In case it's helpful, thishttp://www.onvia.com/business-resources/articles/responding-ifb-rfp-or-rfqis the page I was looking at last night. Rereading it this morning I'm a
> little less sure of my decision, but regardless I'm happy to do whatever
> you guys think is best.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/dobtco/openrfps/pull/8#issuecomment-36034327
> .

## 

Sid Burgess
VP Government Relations
Department of Better Technology
http://dobt.co
@dobtco
206-317-4606

**Comment by ghost** [comment]
Ah, that makes perfect sense. Thanks, @sidburgess! 

After Sid's note I did a bit more digging and found a [separate site that seems dedicated to Alabama RFPs](http://rfp.alabama.gov/PublicView.aspx) — **not ITBs** — and it looks relatively straightforward. That got me thinking: 

For the sake of consistency and keeping things uncomplicated in the openrfps project's early days, I propose that this PR **not** be merged for now and I'll just keep it on a branch in my fork. That way, any decisions about integrating ITBs into the schema can be punted a bit. From Sid's notes, it sounds like ITBs are a different beast and I definitely don't want to distract from the awesome focus on RFPs with questions about ITB integration when it's not necessary.

I'll then write something for the proper RFP site at the `rfp.alamaba.gov` address and open a new PR for that.

Thoughts?

**Comment by sidburgess** [comment]
So, just for additional information... part of the challenge is that some
agencies and staff don't actually know the difference. I see ITB's for
things that shouldn't be all the time.

I like your idea of keeping things orderly early on but eventually, a
common output will probably be desired by vendors just because you'll
always want to check multiple types anyway.

On Tue, Feb 25, 2014 at 4:02 PM, Kiran Gollakota
notifications@github.comwrote:

> Ah, that makes perfect sense. Thanks, @sidburgesshttps://github.com/sidburgess!
> 
> After Sid's note I did a bit more digging and found a separate site that
> seems dedicated to Alabama RFPs http://rfp.alabama.gov/PublicView.aspx-- _not
> ITBs_ -- and it looks relatively straightforward. That got me thinking:
> 
> For the sake of consistency and keeping things uncomplicated in the
> openrfps project's early days, I propose that this PR _not_ be merged for
> now and I'll just keep it on a branch in my fork. That way, any decisions
> about integrating ITBs into the schema can be punted a bit. From Sid's
> notes, it sounds like ITBs are a different beast and I definitely don't
> want to distract from the awesome focus on RFPs with questions about ITB
> integration when it's not necessary.
> 
> I'll then write something for the proper RFP side at the rfp.alamaba.govaddress and open a new PR for that.
> 
> Thoughts?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/dobtco/openrfps/pull/8#issuecomment-36075107
> .

## 

Sid Burgess
VP Government Relations
Department of Better Technology
http://dobt.co
@dobtco
206-317-4606

**Comment by ghost** [comment]
closing this PR for now and will open a new one for the alabama RFPs site in short order.

**Pull request closed without merging**
